services:
    jsh11.dhtmlx.gantt_factory:
        class: jsh11\DhtmlxBundle\Factory\GanttFactory
        arguments: ["@router","@doctrine.orm.entity_manager"]
        
    jsh11.dhtmlx.twig_extension:
        class: jsh11\DhtmlxBundle\Twig\DhtmlxExtension
        arguments: ["@twig", "@doctrine.orm.entity_manager"]
        tags:
            - { name: twig.extension } 
